// <auto-generated />
using System;
using CompanyManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230524121356_RemoveVacationRequests")]
    partial class RemoveVacationRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8890),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8890),
                            IsDeleted = false,
                            Name = "Private health insurance"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8910),
                            IsDeleted = false,
                            Name = "Foreign language lessons"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8920),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8920),
                            IsDeleted = false,
                            Name = "Remote work"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8940),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8940),
                            IsDeleted = false,
                            Name = "Employee learning and advancement"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8980),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8980),
                            IsDeleted = false,
                            Name = "Paid courses and literature for professional development"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8990),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(8990),
                            IsDeleted = false,
                            Name = "Additional day off for one year of experience (+1 day)"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9010),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9010),
                            IsDeleted = false,
                            Name = "Additional days off for more than three years of experience (+2 days)"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9030),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9030),
                            IsDeleted = false,
                            Name = "Paid sports activities"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9040),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9040),
                            IsDeleted = false,
                            Name = "Parents day off (+1 day)"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9060),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9060),
                            IsDeleted = false,
                            Name = "Courses for team-leader positions"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9180),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9180),
                            IsDeleted = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9200),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9200),
                            IsDeleted = false,
                            Name = "German"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9210),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9210),
                            IsDeleted = false,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9230),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9230),
                            IsDeleted = false,
                            Name = "French"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9240),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9240),
                            IsDeleted = false,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9260),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9260),
                            IsDeleted = false,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9270),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9270),
                            IsDeleted = false,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9290),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9290),
                            IsDeleted = false,
                            Name = "Polish"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9300),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9300),
                            IsDeleted = false,
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9320),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9320),
                            IsDeleted = false,
                            Name = "Serbian"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.ReligiousHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9450),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9450),
                            IsDeleted = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9460),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9460),
                            IsDeleted = false,
                            Name = "AngularJS"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9480),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9480),
                            IsDeleted = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9500),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9500),
                            IsDeleted = false,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9510),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9510),
                            IsDeleted = false,
                            Name = "ReactJS"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9530),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9530),
                            IsDeleted = false,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9540),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9540),
                            IsDeleted = false,
                            Name = "Ruby (Ruby on Rails)"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9600),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9600),
                            IsDeleted = false,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9620),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9620),
                            IsDeleted = false,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9630),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9630),
                            IsDeleted = false,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9650),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9650),
                            IsDeleted = false,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9660),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9660),
                            IsDeleted = false,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9680),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9680),
                            IsDeleted = false,
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9690),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9690),
                            IsDeleted = false,
                            Name = "Jira"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9710),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9710),
                            IsDeleted = false,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9720),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9720),
                            IsDeleted = false,
                            Name = "Object C"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9730),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9730),
                            IsDeleted = false,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9750),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9750),
                            IsDeleted = false,
                            Name = "Xmpp"
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9760),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9760),
                            IsDeleted = false,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9780),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9780),
                            IsDeleted = false,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9790),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9790),
                            IsDeleted = false,
                            Name = "C"
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9810),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9810),
                            IsDeleted = false,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9820),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9820),
                            IsDeleted = false,
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9840),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9840),
                            IsDeleted = false,
                            Name = "Hardware Design / Embedded"
                        },
                        new
                        {
                            Id = 25,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9850),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9850),
                            IsDeleted = false,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 26,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9860),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9860),
                            IsDeleted = false,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 27,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9880),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9880),
                            IsDeleted = false,
                            Name = "Selenium"
                        },
                        new
                        {
                            Id = 28,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9890),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9890),
                            IsDeleted = false,
                            Name = "Appium"
                        },
                        new
                        {
                            Id = 29,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9910),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9910),
                            IsDeleted = false,
                            Name = "TestNG"
                        },
                        new
                        {
                            Id = 30,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9920),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 441, DateTimeKind.Utc).AddTicks(9920),
                            IsDeleted = false,
                            Name = "xUnit"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EmploymentDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreeDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingPositionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkingPositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBenefits");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserReligiousHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReligiousHolidayId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReligiousHolidayId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.WorkingPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkingPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 442, DateTimeKind.Utc).AddTicks(350),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 442, DateTimeKind.Utc).AddTicks(350),
                            IsDeleted = false,
                            Name = "Software developer"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 24, 12, 13, 56, 442, DateTimeKind.Utc).AddTicks(360),
                            DateModified = new DateTime(2023, 5, 24, 12, 13, 56, 442, DateTimeKind.Utc).AddTicks(360),
                            IsDeleted = false,
                            Name = "Designer"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.User", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.WorkingPosition", "WorkingPosition")
                        .WithMany("Users")
                        .HasForeignKey("WorkingPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserStatus");

                    b.Navigation("WorkingPosition");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserBenefit", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Benefit", "Benefit")
                        .WithMany("UserBenefits")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserBenefits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserLanguage", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserReligiousHoliday", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.ReligiousHoliday", "ReligiousHoliday")
                        .WithMany("UserReligiousHolidays")
                        .HasForeignKey("ReligiousHolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserReligiousHolidays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReligiousHoliday");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserSkill", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Vacation", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("Vacations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Benefit", b =>
                {
                    b.Navigation("UserBenefits");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.ReligiousHoliday", b =>
                {
                    b.Navigation("UserReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.User", b =>
                {
                    b.Navigation("UserBenefits");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserReligiousHolidays");

                    b.Navigation("UserSkills");

                    b.Navigation("Vacations");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.WorkingPosition", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
