// <auto-generated />
using System;
using CompanyManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230421105222_RemoveProjectAndNote")]
    partial class RemoveProjectAndNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7330),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7330),
                            Name = "Private health insurance"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7350),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7350),
                            Name = "Foreign language lessons"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7370),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7370),
                            Name = "Remote work"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7380),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7380),
                            Name = "Employee learning and advancement"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7400),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7400),
                            Name = "Paid courses and literature for professional development"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7420),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7420),
                            Name = "Additional day off for one year of experience (+1 day)"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7430),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7430),
                            Name = "Additional days off for more than three years of experience (+2 days)"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7450),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7450),
                            Name = "Paid sports activities"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7460),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7460),
                            Name = "Parents day off (+1 day)"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7480),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7480),
                            Name = "Courses for team-leader positions"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7660),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7660),
                            IsDeleted = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7680),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7680),
                            IsDeleted = false,
                            Name = "German"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7690),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7690),
                            IsDeleted = false,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7710),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7710),
                            IsDeleted = false,
                            Name = "French"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7720),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7720),
                            IsDeleted = false,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7740),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7740),
                            IsDeleted = false,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7750),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7750),
                            IsDeleted = false,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7770),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7770),
                            IsDeleted = false,
                            Name = "Polish"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7780),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7780),
                            IsDeleted = false,
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7800),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7800),
                            IsDeleted = false,
                            Name = "Serbian"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.ReligiousHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending acceptance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accepted"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7980),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(7980),
                            IsDeleted = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8000),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8000),
                            IsDeleted = false,
                            Name = "AngularJS"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8020),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8020),
                            IsDeleted = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8030),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8030),
                            IsDeleted = false,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8050),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8050),
                            IsDeleted = false,
                            Name = "ReactJS"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8070),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8070),
                            IsDeleted = false,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8080),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8090),
                            IsDeleted = false,
                            Name = "Ruby (Ruby on Rails)"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8100),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8100),
                            IsDeleted = false,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8120),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8120),
                            IsDeleted = false,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8130),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8130),
                            IsDeleted = false,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8150),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8150),
                            IsDeleted = false,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8160),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8160),
                            IsDeleted = false,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8180),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8180),
                            IsDeleted = false,
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8190),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8190),
                            IsDeleted = false,
                            Name = "Jira"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8210),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8210),
                            IsDeleted = false,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8220),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8220),
                            IsDeleted = false,
                            Name = "Object C"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8240),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8240),
                            IsDeleted = false,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8260),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8260),
                            IsDeleted = false,
                            Name = "Xmpp"
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8270),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8270),
                            IsDeleted = false,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8290),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8290),
                            IsDeleted = false,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8300),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8300),
                            IsDeleted = false,
                            Name = "C"
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8320),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8320),
                            IsDeleted = false,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8330),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8330),
                            IsDeleted = false,
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8350),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8350),
                            IsDeleted = false,
                            Name = "Hardware Design / Embedded"
                        },
                        new
                        {
                            Id = 25,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8360),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8360),
                            IsDeleted = false,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 26,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8380),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8380),
                            IsDeleted = false,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 27,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8390),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8390),
                            IsDeleted = false,
                            Name = "Selenium"
                        },
                        new
                        {
                            Id = 28,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8400),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8400),
                            IsDeleted = false,
                            Name = "Appium"
                        },
                        new
                        {
                            Id = 29,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8420),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8420),
                            IsDeleted = false,
                            Name = "TestNG"
                        },
                        new
                        {
                            Id = 30,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8430),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8430),
                            IsDeleted = false,
                            Name = "xUnit"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreeDaysLastYear")
                        .HasColumnType("integer");

                    b.Property<int>("FreeDaysThisYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingPositionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkingPositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBenefits");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserReligiousHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReligiousHolidayId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReligiousHolidayId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserWorkingPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserWorkingPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8990),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(8990),
                            Name = "Software developer"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(9000),
                            DateModified = new DateTime(2023, 4, 21, 10, 52, 22, 291, DateTimeKind.Utc).AddTicks(9000),
                            Name = "Designer"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessedById")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<int>("VacationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedById");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("VacationId");

                    b.ToTable("VacationRequests");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.User", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.UserWorkingPosition", "UserWorkingPosition")
                        .WithMany("Users")
                        .HasForeignKey("WorkingPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");

                    b.Navigation("UserStatus");

                    b.Navigation("UserWorkingPosition");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserBenefit", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Benefit", "Benefit")
                        .WithMany("UserBenefits")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserBenefits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserLanguage", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserReligiousHoliday", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.ReligiousHoliday", "ReligiousHoliday")
                        .WithMany("UserReligiousHolidays")
                        .HasForeignKey("ReligiousHolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserReligiousHolidays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReligiousHoliday");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserSkill", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.VacationRequest", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "ProcessedBy")
                        .WithMany("ProcessedVacationRequests")
                        .HasForeignKey("ProcessedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.RequestStatus", "RequestStatus")
                        .WithMany("VacationRequests")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.User", "RequestedBy")
                        .WithMany("RequestedVacationRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Entities.Vacation", "Vacation")
                        .WithMany("VacationRequests")
                        .HasForeignKey("VacationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedBy");

                    b.Navigation("RequestStatus");

                    b.Navigation("RequestedBy");

                    b.Navigation("Vacation");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Benefit", b =>
                {
                    b.Navigation("UserBenefits");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.ReligiousHoliday", b =>
                {
                    b.Navigation("UserReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.RequestStatus", b =>
                {
                    b.Navigation("VacationRequests");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.User", b =>
                {
                    b.Navigation("ProcessedVacationRequests");

                    b.Navigation("RequestedVacationRequests");

                    b.Navigation("UserBenefits");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserReligiousHolidays");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.UserWorkingPosition", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Entities.Vacation", b =>
                {
                    b.Navigation("VacationRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
