// <auto-generated />
using System;
using CompanyManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8540),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8540),
                            Name = "Private health insurance"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8560),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8560),
                            Name = "Foreign language lessons"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8580),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8580),
                            Name = "Remote work"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8590),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8590),
                            Name = "Employee learning and advancement"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8610),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8610),
                            Name = "Paid courses and literature for professional development"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8630),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8630),
                            Name = "Additional day off for one year of experience (+1 day)"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8640),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8640),
                            Name = "Additional days off for more than three years of experience (+2 days)"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8660),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8660),
                            Name = "Paid sports activities"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8670),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8670),
                            Name = "Parents day off (+1 day)"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8690),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8690),
                            Name = "Courses for team-leader positions"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8880),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8880),
                            IsDeleted = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8890),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8890),
                            IsDeleted = false,
                            Name = "German"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8910),
                            IsDeleted = false,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8930),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8930),
                            IsDeleted = false,
                            Name = "French"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8940),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8940),
                            IsDeleted = false,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8960),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8960),
                            IsDeleted = false,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8970),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8970),
                            IsDeleted = false,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8990),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(8990),
                            IsDeleted = false,
                            Name = "Polish"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9000),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9000),
                            IsDeleted = false,
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9020),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9020),
                            IsDeleted = false,
                            Name = "Serbian"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompanys")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectDevelopers");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectDeveloperSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectDeveloperId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectSkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDeveloperId");

                    b.HasIndex("ProjectSkillId");

                    b.ToTable("ProjectDeveloperSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ReligiousHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending acceptance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accepted"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9180),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9180),
                            IsDeleted = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9190),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9190),
                            IsDeleted = false,
                            Name = "AngularJS"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9210),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9210),
                            IsDeleted = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9230),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9230),
                            IsDeleted = false,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9240),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9240),
                            IsDeleted = false,
                            Name = "ReactJS"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9260),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9260),
                            IsDeleted = false,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9270),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9270),
                            IsDeleted = false,
                            Name = "Ruby (Ruby on Rails)"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9290),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9290),
                            IsDeleted = false,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9340),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9340),
                            IsDeleted = false,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9360),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9360),
                            IsDeleted = false,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9380),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9380),
                            IsDeleted = false,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9390),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9390),
                            IsDeleted = false,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9410),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9410),
                            IsDeleted = false,
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9420),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9420),
                            IsDeleted = false,
                            Name = "Jira"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9440),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9440),
                            IsDeleted = false,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9450),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9450),
                            IsDeleted = false,
                            Name = "Object C"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9470),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9470),
                            IsDeleted = false,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9510),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9510),
                            IsDeleted = false,
                            Name = "Xmpp"
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9520),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9520),
                            IsDeleted = false,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9540),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9540),
                            IsDeleted = false,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9550),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9550),
                            IsDeleted = false,
                            Name = "C"
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9570),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9570),
                            IsDeleted = false,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9580),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9580),
                            IsDeleted = false,
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9600),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9600),
                            IsDeleted = false,
                            Name = "Hardware Design / Embedded"
                        },
                        new
                        {
                            Id = 25,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9610),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9610),
                            IsDeleted = false,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 26,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9630),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9630),
                            IsDeleted = false,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 27,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9640),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9640),
                            IsDeleted = false,
                            Name = "Selenium"
                        },
                        new
                        {
                            Id = 28,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9660),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9660),
                            IsDeleted = false,
                            Name = "Appium"
                        },
                        new
                        {
                            Id = 29,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9670),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9670),
                            IsDeleted = false,
                            Name = "TestNG"
                        },
                        new
                        {
                            Id = 30,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9690),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 925, DateTimeKind.Utc).AddTicks(9690),
                            IsDeleted = false,
                            Name = "xUnit"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.SkillRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SkillRatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Doesn't have knowledge.",
                            Name = "R0"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Can't work on a commercial project, doesn't have enough knowledge.",
                            Name = "R1"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Can work on a commercial project but it needs help (mentoring, monitoring).It will need more time for each task and someone experienced must be available during the project.",
                            Name = "R2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Can work on a commercial project independently, but it cannot adapt the work to different contexts or unusual situations, and for complicated cases it will need help.",
                            Name = "R3"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Works completely independently on a commercial project, adapts work to different contexts, introduces innovations, solves complicated cases.",
                            Name = "R4"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreeDaysLastYear")
                        .HasColumnType("integer");

                    b.Property<int>("FreeDaysThisYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingPositionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkingPositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBenefits");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserReligiousHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReligiousHolidayId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReligiousHolidayId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillRatingId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillRatingId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserWorkingPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserWorkingPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 926, DateTimeKind.Utc).AddTicks(420),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 926, DateTimeKind.Utc).AddTicks(420),
                            Name = "Software developer"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 4, 13, 20, 3, 14, 926, DateTimeKind.Utc).AddTicks(430),
                            DateModified = new DateTime(2023, 4, 13, 20, 3, 14, 926, DateTimeKind.Utc).AddTicks(430),
                            Name = "Designer"
                        });
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessedById")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<int>("VacationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedById");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("VacationId");

                    b.ToTable("VacationRequests");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Note", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.User", "AssignedTo")
                        .WithMany("AssignedNotes")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "CreatedBy")
                        .WithMany("CreatedNotes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectDeveloper", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.Project", "Project")
                        .WithMany("ProjectDevelopers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "User")
                        .WithMany("ProjectDevelopers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectDeveloperSkill", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.ProjectDeveloper", "ProjectDeveloper")
                        .WithMany("DeveloperSkills")
                        .HasForeignKey("ProjectDeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.ProjectSkill", "ProjectSkill")
                        .WithMany("DeveloperSkills")
                        .HasForeignKey("ProjectSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectDeveloper");

                    b.Navigation("ProjectSkill");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectSkill", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.User", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.UserWorkingPosition", "UserWorkingPosition")
                        .WithMany("Users")
                        .HasForeignKey("WorkingPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");

                    b.Navigation("UserStatus");

                    b.Navigation("UserWorkingPosition");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserBenefit", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.Benefit", "Benefit")
                        .WithMany("UserBenefits")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "User")
                        .WithMany("UserBenefits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserLanguage", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserReligiousHoliday", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.ReligiousHoliday", "ReligiousHoliday")
                        .WithMany("UserReligiousHolidays")
                        .HasForeignKey("ReligiousHolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "User")
                        .WithMany("UserReligiousHolidays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReligiousHoliday");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserSkill", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.SkillRating", "SkillRating")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("SkillRating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.VacationRequest", b =>
                {
                    b.HasOne("CompanyManagementSystem.Data.Models.User", "ProcessedBy")
                        .WithMany("ProcessedVacationRequests")
                        .HasForeignKey("ProcessedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.RequestStatus", "RequestStatus")
                        .WithMany("VacationRequests")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.User", "RequestedBy")
                        .WithMany("RequestedVacationRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyManagementSystem.Data.Models.Vacation", "Vacation")
                        .WithMany("VacationRequests")
                        .HasForeignKey("VacationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedBy");

                    b.Navigation("RequestStatus");

                    b.Navigation("RequestedBy");

                    b.Navigation("Vacation");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Benefit", b =>
                {
                    b.Navigation("UserBenefits");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Project", b =>
                {
                    b.Navigation("ProjectDevelopers");

                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectDeveloper", b =>
                {
                    b.Navigation("DeveloperSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ProjectSkill", b =>
                {
                    b.Navigation("DeveloperSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.ReligiousHoliday", b =>
                {
                    b.Navigation("UserReligiousHolidays");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.RequestStatus", b =>
                {
                    b.Navigation("VacationRequests");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Skill", b =>
                {
                    b.Navigation("ProjectSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.SkillRating", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.User", b =>
                {
                    b.Navigation("AssignedNotes");

                    b.Navigation("CreatedNotes");

                    b.Navigation("ProcessedVacationRequests");

                    b.Navigation("ProjectDevelopers");

                    b.Navigation("RequestedVacationRequests");

                    b.Navigation("UserBenefits");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserReligiousHolidays");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.UserWorkingPosition", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CompanyManagementSystem.Data.Models.Vacation", b =>
                {
                    b.Navigation("VacationRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
